version: "3.9"
services:
  apigateway:
    container_name: "api-gateway"
    build:
      context: .
    ports:
      - "8080:5000"
    networks:
      [backend]
  

networks:
  backend:
    external: true
