version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - payment-db
    networks: [backend]

  payment-db:
    image: mysql
    cap_add: 
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: paymentservice
      MYSQL_USER: payment
      MYSQL_PASSWORD: payment
      MYSQL_ROOT_PASSWORD: payment
    volumes:
      - .dbdata:/var/lib/mysql
    
    ports:
      - 3309:3306
    networks: [backend]


networks:
  backend:
    external: true