"""intial migration

Revision ID: 7eb8ecdc6198
Revises: 
Create Date: 2021-09-30 11:52:55.087081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb8ecdc6198'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('visa_num', sa.String(length=15), nullable=False),
    sa.Column('passport_num', sa.String(length=15), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=False),
    sa.Column('tel', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('attachment', sa.String(length=50), nullable=True),
    sa.Column('sub_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('initial_screen', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    # ### end Alembic commands ###
